### ISSUE TITLE
Not starting

### ISSUE THREAD

**Issue by janacm** [DarkViolet-ai/remix-simple-chat#1]
Hey I'm not able to get this dev server up and running. Maybe I'm missing some env vars?

```
🚨 No COOKIE_SECRET environment variable set, using default. The app is insecure in production.
node:internal/process/promises:394
    triggerUncaughtException(err, true /* fromPromise */);
    ^

Error: connect ECONNREFUSED ::1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1611:16)
Emitted 'error' event on Commander instance at:
    at RedisSocket.<anonymous> (C:\Users\janac\Documents\GitHub\remix-simple-chat\node_modules\@redis\client\dist\lib\client\index.js:412:14)
    at RedisSocket.emit (node:events:519:28)
    at RedisSocket._RedisSocket_connect (C:\Users\janac\Documents\GitHub\remix-simple-chat\node_modules\@redis\client\dist\lib\client\socket.js:166:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Commander.connect (C:\Users\janac\Documents\GitHub\remix-simple-chat\node_modules\@redis\client\dist\lib\client\index.js:185:9) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '::1',
  port: 6379
}

```

**Comment by dwcarr** [comment]
Yes, per the readme you need the following in your .env: (the providers are optional, depending on which one you want to use)

REDIS_URL # a redis url, e.g. redis://localhost:6379
DEEP_INFRA_API_KEY # from https://deepinfra.com
TOGETHER_AI_API_KEY # from https://www.together.ai
COOKIE_SECRET # a random string
PINECONE_API_KEY # from https://www.pinecone.io

Let me know if you need any help.

Note, the RAG stuff might need to be overhauled because langchain seems to have broken some stuff.  I am going to rewrite this and rip out all of the langchain soon.

**Comment by janacm** [comment]
Would love to see a version without Langchain, thx!

**Comment by dwcarr** [comment]
Took langchain out of the retrieval demo entirely.
